### PR TITLE
Adding a reference to muextensions

### PR DESCRIPTION
**Pull request by pedrohdz**
- https://github.com/pedrohdz/muextensions/

### CODE REVIEW

**Comment by pedrohdz** [comment]
Hey!
I hope you folks do not mind my adding a plug to my `muextensions` project.  I think it would be useful for people that would like to embed and directly render `ditaa` art in their *reStructuredText* documents.

Thanks!

**Comment by stathissideris** [comment]
Sure no problem. What about hovercraft? Does it support ditaa as well?

**Comment by pedrohdz** [comment]
Hovercraft does not support it out of the box.  I have a PR open with the team to add plugin support directly into Hovercraft (regebro/hovercraft#196).  I am hoping for general feedback from the Hovercraft team before going all in on a solution.  I will start working on cleaning all that up regardless within the next couple of weeks.

For now, this is how you would get it to work with Hovercraft:

- https://github.com/pedrohdz/muextensions#hovercraft

**Comment by pedrohdz** [comment]
Thank you!

**Pull request merged**
